const counter = require("./myModule")
const {inc, dec, getCount} = require("./myModule")
console.log("Count before modification")
console.log(counter.getCount())
counter.inc()
counter.inc()
counter.inc()
counter.dec()
counter.dec()
counter.inc()
inc()
console.log("Count after modification")
console.log(counter.getCount())